apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubedeploy
  template:
    metadata:
      labels:
        app: kubedeploy
    spec:
      containers:
        - name: kubedeploy
          image: ghcr.io/kvngmuhy94/kubedeploy-kubernetes-platform:latest
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: kubedeploy-config
            - secretRef:
                name: kubedeploy-secret

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
