apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubedeploy-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: kubedeploy.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubedeploy-service
                port:
                  number: 80
